/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.DataHandler;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


/**
 *
 * @author mphel
 */
public class Books extends javax.swing.JFrame {

    /**
     * Creates new form Books
     */
    public Books() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vw_btn = new javax.swing.JButton();
        add_btn = new javax.swing.JButton();
        upt_btn = new javax.swing.JButton();
        dlt_btn = new javax.swing.JButton();
        bkID_txt = new javax.swing.JTextField();
        author_txt = new javax.swing.JTextField();
        bkGenre_txt = new javax.swing.JTextField();
        bkName_txt = new javax.swing.JTextField();
        search_txt = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        book_tbl = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        borrowed_txt = new javax.swing.JTextField();
        borrowedID_txt = new javax.swing.JTextField();
        clear_btn = new javax.swing.JButton();
        rM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 178, 173));

        jLabel1.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book Details");

        jLabel2.setText("Book_ID:");

        jLabel3.setText("Book_Genre:");

        jLabel4.setText("Book_Name :");

        jLabel5.setText("Author: ");

        vw_btn.setText("View Books");
        vw_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vw_btnActionPerformed(evt);
            }
        });

        add_btn.setText("Add Book");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        upt_btn.setText("Update Book");
        upt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upt_btnActionPerformed(evt);
            }
        });

        dlt_btn.setText("Delete ");
        dlt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlt_btnActionPerformed(evt);
            }
        });

        bkID_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkID_txtActionPerformed(evt);
            }
        });

        author_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                author_txtActionPerformed(evt);
            }
        });

        search_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_txtActionPerformed(evt);
            }
        });

        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        book_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Book ID", "Book Name", "Genre", "Author", "Borrowed", "Borrower ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(book_tbl);

        jLabel6.setText("Borrower_ID");

        jLabel7.setText("Borrowed:");

        borrowed_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowed_txtActionPerformed(evt);
            }
        });

        borrowedID_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowedID_txtActionPerformed(evt);
            }
        });

        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        rM.setText("Main Menu");
        rM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(vw_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(upt_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dlt_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bkID_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(bkName_txt)
                                    .addComponent(bkGenre_txt)
                                    .addComponent(author_txt)
                                    .addComponent(borrowed_txt)
                                    .addComponent(borrowedID_txt)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(221, 221, 221))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rM)
                .addGap(128, 128, 128))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rM))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_btn)
                    .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(bkID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bkName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bkGenre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(author_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(borrowed_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(borrowedID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlt_btn)
                    .addComponent(upt_btn)
                    .addComponent(add_btn)
                    .addComponent(vw_btn)
                    .addComponent(clear_btn))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_txtActionPerformed

    private void bkID_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkID_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bkID_txtActionPerformed

    private void author_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_author_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_author_txtActionPerformed

    private void borrowed_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowed_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrowed_txtActionPerformed

    private void borrowedID_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowedID_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrowedID_txtActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
        
        try
        {
            String id = bkID_txt.getText();
            String name = bkName_txt.getText();
            String genre = bkGenre_txt.getText();
            String author = author_txt.getText();
            String brw = borrowed_txt.getText();
            String brwID = borrowedID_txt.getText();
            
            if(id.isEmpty()|| name.isEmpty() || genre.isEmpty()|| author.isEmpty()
                    || brw.isEmpty() || brwID.isEmpty())
            {
                 JOptionPane.showMessageDialog(null, 
                "No fields can be left open", 
                "Connection Error", 
                JOptionPane.ERROR_MESSAGE);
            
            
            }
            
            else
            {
                 dl.addBook(id, name, genre, author, brw, brwID);
            }
           
            
    
        }
        catch(Exception ex)
        {
        
            System.out.println(ex.getMessage());

        }
    }//GEN-LAST:event_add_btnActionPerformed

    private void vw_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vw_btnActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) book_tbl.getModel();
        model.setRowCount(0);
        
        try {
            for(String [] row: dl.view())
            {
                model.addRow(row);
            }
            
//        Vector srow = model.getDataVector().elementAt(book_tbl.convertRowIndexToModel(book_tbl.getSelectedRow()));
//        
//        srow.elements();
        } 
        catch (Exception ex) 
        {
            System.out.println(ex.getMessage());
        }
        
        
    }//GEN-LAST:event_vw_btnActionPerformed

    private void upt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upt_btnActionPerformed
        // TODO add your handling code here:
             try
        {
            String id = bkID_txt.getText();
            String name = bkName_txt.getText();
            String genre = bkGenre_txt.getText();
            String author = author_txt.getText();
            String brw = borrowed_txt.getText();
            String brwID = borrowedID_txt.getText();
            
            
            
            if(id.isEmpty()|| name.isEmpty() || genre.isEmpty()|| author.isEmpty()
                    || brw.isEmpty() || brwID.isEmpty())
            {
                JOptionPane.showMessageDialog(null, 
                "No fields can be left open", 
                "Connection Error", 
                JOptionPane.ERROR_MESSAGE);
            }
            
            else
            {
                 dl.updateBook(id, name, genre, author, brw, brwID);
            }
           
            
    
        }
        catch(Exception ex)
        {
        
            System.out.println(ex.getMessage());

        }
    }//GEN-LAST:event_upt_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        
       DefaultTableModel model = (DefaultTableModel) book_tbl.getModel();
       
       int Len = dl.view().size() ;
       int Count = 0;
       String id = search_txt.getText();
       model.setRowCount(0);
       for(String [] row : dl.view())
       {
        
           if (row[0] == null ? id == null : row[0].equals(id))
           {
               
               model.addRow(row);
               bkID_txt.setText(row[0]);
               bkName_txt.setText(row[1]);
               bkGenre_txt.setText(row[2]);
               author_txt.setText(row[3]);
               borrowed_txt.setText(row[4]);
               borrowedID_txt.setText(row[5]);
               break;
           
           }
           
           if( Count == Len -1)
           {
               JOptionPane.showMessageDialog(null, 
                "Book Not Found", 
                "Connection Error", 
                JOptionPane.ERROR);
               
           }
           
           Count ++;
          
       }
       
  
        
    }//GEN-LAST:event_search_btnActionPerformed

    private void dlt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlt_btnActionPerformed
        // TODO add your handling code here:
        //DefaultTableModel model = (DefaultTableModel) book_tbl.getModel();
       
        String id = bkID_txt.getText();
        
         if(id.isEmpty())
            {
                JOptionPane.showMessageDialog(null, 
                "Please enter a bookid", 
                "", 
                JOptionPane.ERROR_MESSAGE);
            
            
            }
            
            else
            {
                 dl.delete(id);
                JOptionPane.showMessageDialog(null, 
                "Record Successfully deleted", 
                "Delete error", 
                JOptionPane.ERROR_MESSAGE);
            }
        
        
    }//GEN-LAST:event_dlt_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
        bkID_txt.setText("");
        bkName_txt.setText("");
        bkGenre_txt.setText("");
        author_txt.setText("");
        borrowed_txt.setText("");
        borrowedID_txt.setText("");
        
        
    }//GEN-LAST:event_clear_btnActionPerformed

    private void rMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rMActionPerformed
        // TODO add your handling code here:
        Main mn = new Main();
        mn.setVisible(true);
        dispose();
    }//GEN-LAST:event_rMActionPerformed

    static DataHandler dl = new DataHandler();
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Books().setVisible(true);
                try
                {
                    dl.getConnection();
                    //dl.create_booktbl();
                    //dl.create_borrowertbl();
                }
                catch(ClassNotFoundException ex)
                {
                    System.out.println(ex.getMessage());
                
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField author_txt;
    private javax.swing.JTextField bkGenre_txt;
    private javax.swing.JTextField bkID_txt;
    private javax.swing.JTextField bkName_txt;
    private javax.swing.JTable book_tbl;
    private javax.swing.JTextField borrowedID_txt;
    private javax.swing.JTextField borrowed_txt;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton dlt_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rM;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField search_txt;
    private javax.swing.JButton upt_btn;
    private javax.swing.JButton vw_btn;
    // End of variables declaration//GEN-END:variables
}
